name: Test & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js 16.x 
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Load cache
      uses: actions/cache@v2
      with:
        path: ~/.yarn
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install environment
      run: |
        sudo apt update
        sudo apt install git chromium-browser
        yarn global add @angular/cli

    - name: Install dependencies
      run: yarn install && ng update

    - name: Check style
      run: |
        yarn eslint '**/*.ts'
        yarn prettier --check '**/*.ts'

    - name: Run tests
      run: yarn test
